name: scrappy

services:
  api:
    build:
      context: ../
      dockerfile: ./ops/api/Dockerfile
    container_name: scrappy_api
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017/scrappy_db
      - ConnectionStrings__Redis=redis:6379
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb
      - redis

  ingestion-worker:
    build:
      context: ../
      dockerfile: ./ops/ingestion/Dockerfile
    container_name: scrappy_ingestion_worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_URL=http://api:5000/events
    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_started
    restart: unless-stopped


  mongodb:
    # image: mongo:latest
    image: mongo:8.3.8-noble
    container_name: scrappy_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: scrappy_db
    volumes:
      - mongo_data:/data/db


  redis:
    # image: redis:alpine
    image: redis:8.10.0-alpine
    container_name: scrappy_redis
    ports:
      - "6379:6379"
    volumes: 
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  redis_data:
  mongo_data:
