name: scrappy

services:
  next:
    build:
      context: ../
      dockerfile: ./ops/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5000
    container_name: scrappy_web
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      api:
        condition: service_started
    restart: unless-stopped

  api:
    build:
      context: ../
      dockerfile: ./ops/api/Dockerfile
    container_name: scrappy_api
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__MongoDb: mongodb://mongodb:27017/scrappy_db
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  ingestion-worker:
    build:
      context: ../
      dockerfile: ./ops/ingestion/Dockerfile
    container_name: scrappy_ingestion_worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_URL=http://api:5000/events
    depends_on:
      redis:
        condition: service_healthy
      api:
        condition: service_started
    restart: unless-stopped

  mongodb:
    build:
      context: ../
      dockerfile: ./ops/mongodb/Dockerfile
    container_name: scrappy_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: scrappy_db
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    build:
      context: ../
      dockerfile: ./ops/redis/Dockerfile
    container_name: scrappy_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  mongo_data:
