

using Scrappy.Models.Entities;
using Scrappy.Models;
using Scrappy.Services.Interfaces;

namespace Scrappy.Services;

public sealed class GeoDataService : IGeoDataService
{
    public (DistrictName? District, Nuts2Region Region, string DicoCode)? Lookup(LocalityName locality)
    {
        return locality switch
        {
            // 01 - AVEIRO
            LocalityName.Águeda => (DistrictName.Aveiro, Nuts2Region.PT16, "0101"),
            LocalityName.AlbergariaAVelha => (DistrictName.Aveiro, Nuts2Region.PT16, "0102"),
            LocalityName.Anadia => (DistrictName.Aveiro, Nuts2Region.PT16, "0103"),
            LocalityName.Arouca => (DistrictName.Aveiro, Nuts2Region.PT11, "0104"),
            LocalityName.Aveiro => (DistrictName.Aveiro, Nuts2Region.PT16, "0105"),
            LocalityName.CasteloDePaiva => (DistrictName.Aveiro, Nuts2Region.PT11, "0106"),
            LocalityName.Espinho => (DistrictName.Aveiro, Nuts2Region.PT11, "0107"),
            LocalityName.Estarreja => (DistrictName.Aveiro, Nuts2Region.PT16, "0108"),
            LocalityName.SantaMariaDaFeira => (DistrictName.Aveiro, Nuts2Region.PT11, "0109"),
            LocalityName.Ílhavo => (DistrictName.Aveiro, Nuts2Region.PT16, "0110"),
            LocalityName.Mealhada => (DistrictName.Aveiro, Nuts2Region.PT16, "0111"),
            LocalityName.Murtosa => (DistrictName.Aveiro, Nuts2Region.PT16, "0112"),
            LocalityName.OliveiraDeAzeméis => (DistrictName.Aveiro, Nuts2Region.PT11, "0113"),
            LocalityName.OliveiraDoBairro => (DistrictName.Aveiro, Nuts2Region.PT16, "0114"),
            LocalityName.Ovar => (DistrictName.Aveiro, Nuts2Region.PT16, "0115"),
            LocalityName.SãoJoãoDaMadeira => (DistrictName.Aveiro, Nuts2Region.PT11, "0116"),
            LocalityName.SeverDoVouga => (DistrictName.Aveiro, Nuts2Region.PT16, "0117"),
            LocalityName.Vagos => (DistrictName.Aveiro, Nuts2Region.PT16, "0118"),
            LocalityName.ValeDeCambra => (DistrictName.Aveiro, Nuts2Region.PT11, "0119"),

            // 02 - BEJA
            LocalityName.Aljustrel => (DistrictName.Beja, Nuts2Region.PT18, "0201"),
            LocalityName.Almodôvar => (DistrictName.Beja, Nuts2Region.PT18, "0202"),
            LocalityName.Alvito => (DistrictName.Beja, Nuts2Region.PT18, "0203"),
            LocalityName.Barrancos => (DistrictName.Beja, Nuts2Region.PT18, "0204"),
            LocalityName.Beja => (DistrictName.Beja, Nuts2Region.PT18, "0205"),
            LocalityName.CastroVerde => (DistrictName.Beja, Nuts2Region.PT18, "0206"),
            LocalityName.Cuba => (DistrictName.Beja, Nuts2Region.PT18, "0207"),
            LocalityName.FerreiraDoAlentejo => (DistrictName.Beja, Nuts2Region.PT18, "0208"),
            LocalityName.Mértola => (DistrictName.Beja, Nuts2Region.PT18, "0209"),
            LocalityName.Moura => (DistrictName.Beja, Nuts2Region.PT18, "0210"),
            LocalityName.Odemira => (DistrictName.Beja, Nuts2Region.PT18, "0211"),
            LocalityName.Ourique => (DistrictName.Beja, Nuts2Region.PT18, "0212"),
            LocalityName.Serpa => (DistrictName.Beja, Nuts2Region.PT18, "0213"),
            LocalityName.Vidigueira => (DistrictName.Beja, Nuts2Region.PT18, "0214"),

            // 03 - BRAGA
            LocalityName.Amares => (DistrictName.Braga, Nuts2Region.PT11, "0301"),
            LocalityName.Barcelos => (DistrictName.Braga, Nuts2Region.PT11, "0302"),
            LocalityName.Braga => (DistrictName.Braga, Nuts2Region.PT11, "0303"),
            LocalityName.CabeceirasDeBasto => (DistrictName.Braga, Nuts2Region.PT11, "0304"),
            LocalityName.CeloricoDeBasto => (DistrictName.Braga, Nuts2Region.PT11, "0305"),
            LocalityName.Esposende => (DistrictName.Braga, Nuts2Region.PT11, "0306"),
            LocalityName.Fafe => (DistrictName.Braga, Nuts2Region.PT11, "0307"),
            LocalityName.Guimarães => (DistrictName.Braga, Nuts2Region.PT11, "0308"),
            LocalityName.PóvoaDeLanhoso => (DistrictName.Braga, Nuts2Region.PT11, "0309"),
            LocalityName.TerrasDeBouro => (DistrictName.Braga, Nuts2Region.PT11, "0310"),
            LocalityName.VieiraDoMinho => (DistrictName.Braga, Nuts2Region.PT11, "0311"),
            LocalityName.VilaNovaDeFamalicão => (DistrictName.Braga, Nuts2Region.PT11, "0312"),
            LocalityName.VilaVerde => (DistrictName.Braga, Nuts2Region.PT11, "0313"),
            LocalityName.Vizela => (DistrictName.Braga, Nuts2Region.PT11, "0314"),

            // 04 - BRAGANÇA
            LocalityName.AlfândegaDaFé => (DistrictName.Bragança, Nuts2Region.PT11, "0401"),
            LocalityName.Bragança => (DistrictName.Bragança, Nuts2Region.PT11, "0402"),
            LocalityName.CarrazedaDeAnsiães => (DistrictName.Bragança, Nuts2Region.PT11, "0403"),
            LocalityName.FreixoDeEspadaÀCinta => (DistrictName.Bragança, Nuts2Region.PT11, "0404"),
            LocalityName.MacedoDeCavaleiros => (DistrictName.Bragança, Nuts2Region.PT11, "0405"),
            LocalityName.MirandaDoDouro => (DistrictName.Bragança, Nuts2Region.PT11, "0406"),
            LocalityName.Mirandela => (DistrictName.Bragança, Nuts2Region.PT11, "0407"),
            LocalityName.Mogadouro => (DistrictName.Bragança, Nuts2Region.PT11, "0408"),
            LocalityName.TorreDeMoncorvo => (DistrictName.Bragança, Nuts2Region.PT11, "0409"),
            LocalityName.VilaFlor => (DistrictName.Bragança, Nuts2Region.PT11, "0410"),
            LocalityName.Vimioso => (DistrictName.Bragança, Nuts2Region.PT11, "0411"),
            LocalityName.Vinhais => (DistrictName.Bragança, Nuts2Region.PT11, "0412"),

            // 05 - CASTELO BRANCO
            LocalityName.Belmonte => (DistrictName.CasteloBranco, Nuts2Region.PT16, "0501"),
            LocalityName.CasteloBranco => (DistrictName.CasteloBranco, Nuts2Region.PT16, "0502"),
            LocalityName.Covilhã => (DistrictName.CasteloBranco, Nuts2Region.PT16, "0503"),
            LocalityName.Fundão => (DistrictName.CasteloBranco, Nuts2Region.PT16, "0504"),
            LocalityName.IdanhaANova => (DistrictName.CasteloBranco, Nuts2Region.PT16, "0505"),
            LocalityName.Oleiros => (DistrictName.CasteloBranco, Nuts2Region.PT16, "0506"),
            LocalityName.Penamacor => (DistrictName.CasteloBranco, Nuts2Region.PT16, "0507"),
            LocalityName.ProençaANova => (DistrictName.CasteloBranco, Nuts2Region.PT16, "0508"),
            LocalityName.Sertã => (DistrictName.CasteloBranco, Nuts2Region.PT16, "0509"),
            LocalityName.VilaDeRei => (DistrictName.CasteloBranco, Nuts2Region.PT16, "0510"),
            LocalityName.VilaVelhaDeRódão => (DistrictName.CasteloBranco, Nuts2Region.PT16, "0511"),

            // 06 - COIMBRA
            LocalityName.Arganil => (DistrictName.Coimbra, Nuts2Region.PT16, "0601"),
            LocalityName.Cantanhede => (DistrictName.Coimbra, Nuts2Region.PT16, "0602"),
            LocalityName.Coimbra => (DistrictName.Coimbra, Nuts2Region.PT16, "0603"),
            LocalityName.CondeixaANova => (DistrictName.Coimbra, Nuts2Region.PT16, "0604"),
            LocalityName.FigueiraDaFoz => (DistrictName.Coimbra, Nuts2Region.PT16, "0605"),
            LocalityName.Góis => (DistrictName.Coimbra, Nuts2Region.PT16, "0606"),
            LocalityName.Lousã => (DistrictName.Coimbra, Nuts2Region.PT16, "0607"),
            LocalityName.Mira => (DistrictName.Coimbra, Nuts2Region.PT16, "0608"),
            LocalityName.MirandaDoCorvo => (DistrictName.Coimbra, Nuts2Region.PT16, "0609"),
            LocalityName.MontemorOVelho => (DistrictName.Coimbra, Nuts2Region.PT16, "0610"),
            LocalityName.OliveiraDoHospital => (DistrictName.Coimbra, Nuts2Region.PT16, "0611"),
            LocalityName.PampilhosaDaSerra => (DistrictName.Coimbra, Nuts2Region.PT16, "0612"),
            LocalityName.Penacova => (DistrictName.Coimbra, Nuts2Region.PT16, "0613"),
            LocalityName.Penela => (DistrictName.Coimbra, Nuts2Region.PT16, "0614"),
            LocalityName.Soure => (DistrictName.Coimbra, Nuts2Region.PT16, "0615"),
            LocalityName.Tábua => (DistrictName.Coimbra, Nuts2Region.PT16, "0616"),
            LocalityName.VilaNovaDePoiares => (DistrictName.Coimbra, Nuts2Region.PT16, "0617"),

            // 07 - ÉVORA
            LocalityName.Alandroal => (DistrictName.Évora, Nuts2Region.PT18, "0701"),
            LocalityName.Arraiolos => (DistrictName.Évora, Nuts2Region.PT18, "0702"),
            LocalityName.Borba => (DistrictName.Évora, Nuts2Region.PT18, "0703"),
            LocalityName.Estremoz => (DistrictName.Évora, Nuts2Region.PT18, "0704"),
            LocalityName.Évora => (DistrictName.Évora, Nuts2Region.PT18, "0705"),
            LocalityName.MontemorONovo => (DistrictName.Évora, Nuts2Region.PT18, "0706"),
            LocalityName.Mora => (DistrictName.Évora, Nuts2Region.PT18, "0707"),
            LocalityName.Mourão => (DistrictName.Évora, Nuts2Region.PT18, "0708"),
            LocalityName.Portel => (DistrictName.Évora, Nuts2Region.PT18, "0709"),
            LocalityName.Redondo => (DistrictName.Évora, Nuts2Region.PT18, "0710"),
            LocalityName.ReguengosDeMonsaraz => (DistrictName.Évora, Nuts2Region.PT18, "0711"),
            LocalityName.VendasNovas => (DistrictName.Évora, Nuts2Region.PT18, "0712"),
            LocalityName.VianaDoAlentejo => (DistrictName.Évora, Nuts2Region.PT18, "0713"),
            LocalityName.VilaViçosa => (DistrictName.Évora, Nuts2Region.PT18, "0714"),

            // 08 - FARO
            LocalityName.Albufeira => (DistrictName.Faro, Nuts2Region.PT15, "0801"),
            LocalityName.Alcoutim => (DistrictName.Faro, Nuts2Region.PT15, "0802"),
            LocalityName.Aljezur => (DistrictName.Faro, Nuts2Region.PT15, "0803"),
            LocalityName.CastroMarim => (DistrictName.Faro, Nuts2Region.PT15, "0804"),
            LocalityName.Faro => (DistrictName.Faro, Nuts2Region.PT15, "0805"),
            LocalityName.LagoaAlgarve => (DistrictName.Faro, Nuts2Region.PT15, "0806"),
            LocalityName.Lagos => (DistrictName.Faro, Nuts2Region.PT15, "0807"),
            LocalityName.Loulé => (DistrictName.Faro, Nuts2Region.PT15, "0808"),
            LocalityName.Monchique => (DistrictName.Faro, Nuts2Region.PT15, "0809"),
            LocalityName.Olhão => (DistrictName.Faro, Nuts2Region.PT15, "0810"),
            LocalityName.Portimão => (DistrictName.Faro, Nuts2Region.PT15, "0811"),
            LocalityName.SãoBrásDeAlportel => (DistrictName.Faro, Nuts2Region.PT15, "0812"),
            LocalityName.Silves => (DistrictName.Faro, Nuts2Region.PT15, "0813"),
            LocalityName.Tavira => (DistrictName.Faro, Nuts2Region.PT15, "0814"),
            LocalityName.VilaDoBispo => (DistrictName.Faro, Nuts2Region.PT15, "0815"),
            LocalityName.VilaRealDeSantoAntónio => (DistrictName.Faro, Nuts2Region.PT15, "0816"),

            // 09 - GUARDA
            LocalityName.AguiarDaBeira => (DistrictName.Guarda, Nuts2Region.PT16, "0901"),
            LocalityName.Almeida => (DistrictName.Guarda, Nuts2Region.PT16, "0902"),
            LocalityName.CeloricoDaBeira => (DistrictName.Guarda, Nuts2Region.PT16, "0903"),
            LocalityName.FigueiraDeCasteloRodrigo => (DistrictName.Guarda, Nuts2Region.PT16, "0904"),
            LocalityName.FornosDeAlgodres => (DistrictName.Guarda, Nuts2Region.PT16, "0905"),
            LocalityName.Gouveia => (DistrictName.Guarda, Nuts2Region.PT16, "0906"),
            LocalityName.Guarda => (DistrictName.Guarda, Nuts2Region.PT16, "0907"),
            LocalityName.Manteigas => (DistrictName.Guarda, Nuts2Region.PT16, "0908"),
            LocalityName.Mêda => (DistrictName.Guarda, Nuts2Region.PT16, "0909"),
            LocalityName.Pinhel => (DistrictName.Guarda, Nuts2Region.PT16, "0910"),
            LocalityName.Sabugal => (DistrictName.Guarda, Nuts2Region.PT16, "0911"),
            LocalityName.Seia => (DistrictName.Guarda, Nuts2Region.PT16, "0912"),
            LocalityName.Trancoso => (DistrictName.Guarda, Nuts2Region.PT16, "0913"),
            LocalityName.VilaNovaDeFozCôa => (DistrictName.Guarda, Nuts2Region.PT16, "0914"),

            // 10 - LEIRIA
            LocalityName.Alcobaça => (DistrictName.Leiria, Nuts2Region.PT1C, "1001"),
            LocalityName.Alvaiázere => (DistrictName.Leiria, Nuts2Region.PT16, "1002"),
            LocalityName.Ansião => (DistrictName.Leiria, Nuts2Region.PT16, "1003"),
            LocalityName.Batalha => (DistrictName.Leiria, Nuts2Region.PT16, "1004"),
            LocalityName.Bombarral => (DistrictName.Leiria, Nuts2Region.PT1C, "1005"),
            LocalityName.CaldasDaRainha => (DistrictName.Leiria, Nuts2Region.PT1C, "1006"),
            LocalityName.CastanheiraDePera => (DistrictName.Leiria, Nuts2Region.PT16, "1007"),
            LocalityName.FigueiróDosVinhos => (DistrictName.Leiria, Nuts2Region.PT16, "1008"),
            LocalityName.Leiria => (DistrictName.Leiria, Nuts2Region.PT16, "1009"),
            LocalityName.MarinhaGrande => (DistrictName.Leiria, Nuts2Region.PT16, "1010"),
            LocalityName.Nazaré => (DistrictName.Leiria, Nuts2Region.PT1C, "1011"),
            LocalityName.Óbidos => (DistrictName.Leiria, Nuts2Region.PT1C, "1012"),
            LocalityName.PedrógãoGrande => (DistrictName.Leiria, Nuts2Region.PT16, "1013"),
            LocalityName.Peniche => (DistrictName.Leiria, Nuts2Region.PT1C, "1014"),
            LocalityName.Pombal => (DistrictName.Leiria, Nuts2Region.PT16, "1015"),
            LocalityName.PortoDeMós => (DistrictName.Leiria, Nuts2Region.PT16, "1016"),

            // 11 - LISBOA
            LocalityName.Alenquer => (DistrictName.Lisboa, Nuts2Region.PT1C, "1101"),
            LocalityName.ArrudaDosVinhos => (DistrictName.Lisboa, Nuts2Region.PT1C, "1102"),
            LocalityName.Azambuja => (DistrictName.Lisboa, Nuts2Region.PT1C, "1103"),
            LocalityName.Cadaval => (DistrictName.Lisboa, Nuts2Region.PT1C, "1104"),
            LocalityName.Cascais => (DistrictName.Lisboa, Nuts2Region.PT1A, "1105"),
            LocalityName.Lisboa => (DistrictName.Lisboa, Nuts2Region.PT1A, "1106"),
            LocalityName.Loures => (DistrictName.Lisboa, Nuts2Region.PT1A, "1107"),
            LocalityName.Lourinhã => (DistrictName.Lisboa, Nuts2Region.PT1C, "1108"),
            LocalityName.Mafra => (DistrictName.Lisboa, Nuts2Region.PT1A, "1109"),
            LocalityName.Oeiras => (DistrictName.Lisboa, Nuts2Region.PT1A, "1110"),
            LocalityName.Sintra => (DistrictName.Lisboa, Nuts2Region.PT1A, "1111"),
            LocalityName.SobralDeMonteAgraço => (DistrictName.Lisboa, Nuts2Region.PT1C, "1112"),
            LocalityName.TorresVedras => (DistrictName.Lisboa, Nuts2Region.PT1C, "1113"),
            LocalityName.VilaFrancaDeXira => (DistrictName.Lisboa, Nuts2Region.PT1A, "1114"),
            LocalityName.Amadora => (DistrictName.Lisboa, Nuts2Region.PT1A, "1115"),
            LocalityName.Odivelas => (DistrictName.Lisboa, Nuts2Region.PT1A, "1116"),

            // 12 - PORTALEGRE
            LocalityName.AlterDoChão => (DistrictName.Portalegre, Nuts2Region.PT18, "1201"),
            LocalityName.Arronches => (DistrictName.Portalegre, Nuts2Region.PT18, "1202"),
            LocalityName.Avis => (DistrictName.Portalegre, Nuts2Region.PT18, "1203"),
            LocalityName.CampoMaior => (DistrictName.Portalegre, Nuts2Region.PT18, "1204"),
            LocalityName.CasteloDeVide => (DistrictName.Portalegre, Nuts2Region.PT18, "1205"),
            LocalityName.Crato => (DistrictName.Portalegre, Nuts2Region.PT18, "1206"),
            LocalityName.Elvas => (DistrictName.Portalegre, Nuts2Region.PT18, "1207"),
            LocalityName.Fronteira => (DistrictName.Portalegre, Nuts2Region.PT18, "1208"),
            LocalityName.Gavião => (DistrictName.Portalegre, Nuts2Region.PT18, "1209"),
            LocalityName.Marvão => (DistrictName.Portalegre, Nuts2Region.PT18, "1210"),
            LocalityName.Monforte => (DistrictName.Portalegre, Nuts2Region.PT18, "1211"),
            LocalityName.Nisa => (DistrictName.Portalegre, Nuts2Region.PT18, "1212"),
            LocalityName.PonteDeSor => (DistrictName.Portalegre, Nuts2Region.PT18, "1213"),
            LocalityName.Portalegre => (DistrictName.Portalegre, Nuts2Region.PT18, "1214"),
            LocalityName.Sousel => (DistrictName.Portalegre, Nuts2Region.PT18, "1215"),

            // 13 - PORTO
            LocalityName.Amarante => (DistrictName.Porto, Nuts2Region.PT11, "1301"),
            LocalityName.Baião => (DistrictName.Porto, Nuts2Region.PT11, "1302"),
            LocalityName.Felgueiras => (DistrictName.Porto, Nuts2Region.PT11, "1303"),
            LocalityName.Gondomar => (DistrictName.Porto, Nuts2Region.PT11, "1304"),
            LocalityName.Lousada => (DistrictName.Porto, Nuts2Region.PT11, "1305"),
            LocalityName.Maia => (DistrictName.Porto, Nuts2Region.PT11, "1306"),
            LocalityName.MarcoDeCanaveses => (DistrictName.Porto, Nuts2Region.PT11, "1307"),
            LocalityName.Matosinhos => (DistrictName.Porto, Nuts2Region.PT11, "1308"),
            LocalityName.PaçosDeFerreira => (DistrictName.Porto, Nuts2Region.PT11, "1309"),
            LocalityName.Paredes => (DistrictName.Porto, Nuts2Region.PT11, "1310"),
            LocalityName.Penafiel => (DistrictName.Porto, Nuts2Region.PT11, "1311"),
            LocalityName.Porto => (DistrictName.Porto, Nuts2Region.PT11, "1312"),
            LocalityName.PóvoaDeVarzim => (DistrictName.Porto, Nuts2Region.PT11, "1313"),
            LocalityName.SantoTirso => (DistrictName.Porto, Nuts2Region.PT11, "1314"),
            LocalityName.Valongo => (DistrictName.Porto, Nuts2Region.PT11, "1315"),
            LocalityName.VilaDoConde => (DistrictName.Porto, Nuts2Region.PT11, "1316"),
            LocalityName.VilaNovaDeGaia => (DistrictName.Porto, Nuts2Region.PT11, "1317"),
            LocalityName.Trofa => (DistrictName.Porto, Nuts2Region.PT11, "1318"),

            // 14 - SANTARÉM
            LocalityName.Abrantes => (DistrictName.Santarém, Nuts2Region.PT1C, "1401"),
            LocalityName.Alcanena => (DistrictName.Santarém, Nuts2Region.PT1C, "1402"),
            LocalityName.Almeirim => (DistrictName.Santarém, Nuts2Region.PT1C, "1403"),
            LocalityName.Alpiarça => (DistrictName.Santarém, Nuts2Region.PT1C, "1404"),
            LocalityName.Benavente => (DistrictName.Santarém, Nuts2Region.PT1C, "1405"),
            LocalityName.Cartaxo => (DistrictName.Santarém, Nuts2Region.PT1C, "1406"),
            LocalityName.Chamusca => (DistrictName.Santarém, Nuts2Region.PT1C, "1407"),
            LocalityName.Constância => (DistrictName.Santarém, Nuts2Region.PT1C, "1408"),
            LocalityName.Coruche => (DistrictName.Santarém, Nuts2Region.PT1C, "1409"),
            LocalityName.Entroncamento => (DistrictName.Santarém, Nuts2Region.PT1C, "1410"),
            LocalityName.FerreiraDoZêzere => (DistrictName.Santarém, Nuts2Region.PT1C, "1411"),
            LocalityName.Golegã => (DistrictName.Santarém, Nuts2Region.PT1C, "1412"),
            LocalityName.Mação => (DistrictName.Santarém, Nuts2Region.PT1C, "1413"),
            LocalityName.RioMaior => (DistrictName.Santarém, Nuts2Region.PT1C, "1414"),
            LocalityName.SalvaterraDeMagos => (DistrictName.Santarém, Nuts2Region.PT1C, "1415"),
            LocalityName.Santarém => (DistrictName.Santarém, Nuts2Region.PT1C, "1416"),
            LocalityName.Sardoal => (DistrictName.Santarém, Nuts2Region.PT1C, "1417"),
            LocalityName.Tomar => (DistrictName.Santarém, Nuts2Region.PT1C, "1418"),
            LocalityName.TorresNovas => (DistrictName.Santarém, Nuts2Region.PT1C, "1419"),
            LocalityName.VilaNovaDaBarquinha => (DistrictName.Santarém, Nuts2Region.PT1C, "1420"),
            LocalityName.Ourém => (DistrictName.Santarém, Nuts2Region.PT1C, "1421"),

            // 15 - SETÚBAL
            LocalityName.AlcácerDoSal => (DistrictName.Setúbal, Nuts2Region.PT18, "1501"),
            LocalityName.Alcochete => (DistrictName.Setúbal, Nuts2Region.PT1B, "1502"),
            LocalityName.Almada => (DistrictName.Setúbal, Nuts2Region.PT1B, "1503"),
            LocalityName.Barreiro => (DistrictName.Setúbal, Nuts2Region.PT1B, "1504"),
            LocalityName.Grândola => (DistrictName.Setúbal, Nuts2Region.PT18, "1505"),
            LocalityName.Moita => (DistrictName.Setúbal, Nuts2Region.PT1B, "1506"),
            LocalityName.Montijo => (DistrictName.Setúbal, Nuts2Region.PT1B, "1507"),
            LocalityName.Palmela => (DistrictName.Setúbal, Nuts2Region.PT1B, "1508"),
            LocalityName.SantiagoDoCacém => (DistrictName.Setúbal, Nuts2Region.PT18, "1509"),
            LocalityName.Seixal => (DistrictName.Setúbal, Nuts2Region.PT1B, "1510"),
            LocalityName.Sesimbra => (DistrictName.Setúbal, Nuts2Region.PT1B, "1511"),
            LocalityName.Setúbal => (DistrictName.Setúbal, Nuts2Region.PT1B, "1512"),
            LocalityName.Sines => (DistrictName.Setúbal, Nuts2Region.PT18, "1513"),

            // 16 - VIANA DO CASTELO
            LocalityName.ArcosDeValdevez => (DistrictName.VianaDoCastelo, Nuts2Region.PT11, "1601"),
            LocalityName.Caminha => (DistrictName.VianaDoCastelo, Nuts2Region.PT11, "1602"),
            LocalityName.Melgaço => (DistrictName.VianaDoCastelo, Nuts2Region.PT11, "1603"),
            LocalityName.Monção => (DistrictName.VianaDoCastelo, Nuts2Region.PT11, "1604"),
            LocalityName.ParedesDeCoura => (DistrictName.VianaDoCastelo, Nuts2Region.PT11, "1605"),
            LocalityName.PonteDaBarca => (DistrictName.VianaDoCastelo, Nuts2Region.PT11, "1606"),
            LocalityName.PonteDeLima => (DistrictName.VianaDoCastelo, Nuts2Region.PT11, "1607"),
            LocalityName.Valença => (DistrictName.VianaDoCastelo, Nuts2Region.PT11, "1608"),
            LocalityName.VianaDoCastelo => (DistrictName.VianaDoCastelo, Nuts2Region.PT11, "1609"),
            LocalityName.VilaNovaDeCerveira => (DistrictName.VianaDoCastelo, Nuts2Region.PT11, "1610"),

            // 17 - VILA REAL
            LocalityName.Alijó => (DistrictName.VilaReal, Nuts2Region.PT11, "1701"),
            LocalityName.Boticas => (DistrictName.VilaReal, Nuts2Region.PT11, "1702"),
            LocalityName.Chaves => (DistrictName.VilaReal, Nuts2Region.PT11, "1703"),
            LocalityName.MesãoFrio => (DistrictName.VilaReal, Nuts2Region.PT11, "1704"),
            LocalityName.MondimDeBasto => (DistrictName.VilaReal, Nuts2Region.PT11, "1705"),
            LocalityName.Montalegre => (DistrictName.VilaReal, Nuts2Region.PT11, "1706"),
            LocalityName.Murça => (DistrictName.VilaReal, Nuts2Region.PT11, "1707"),
            LocalityName.PesoDaRégua => (DistrictName.VilaReal, Nuts2Region.PT11, "1708"),
            LocalityName.RibeiraDePena => (DistrictName.VilaReal, Nuts2Region.PT11, "1709"),
            LocalityName.Sabrosa => (DistrictName.VilaReal, Nuts2Region.PT11, "1710"),
            LocalityName.SantaMartaDePenaguião => (DistrictName.VilaReal, Nuts2Region.PT11, "1711"),
            LocalityName.Valpaços => (DistrictName.VilaReal, Nuts2Region.PT11, "1712"),
            LocalityName.VilaPoucaDeAguiar => (DistrictName.VilaReal, Nuts2Region.PT11, "1713"),
            LocalityName.VilaReal => (DistrictName.VilaReal, Nuts2Region.PT11, "1714"),

            // 18 - VISEU
            LocalityName.Armamar => (DistrictName.Viseu, Nuts2Region.PT11, "1801"),
            LocalityName.CarregalDoSal => (DistrictName.Viseu, Nuts2Region.PT16, "1802"),
            LocalityName.CastroDaire => (DistrictName.Viseu, Nuts2Region.PT16, "1803"),
            LocalityName.Cinfães => (DistrictName.Viseu, Nuts2Region.PT11, "1804"),
            LocalityName.Lamego => (DistrictName.Viseu, Nuts2Region.PT11, "1805"),
            LocalityName.Mangualde => (DistrictName.Viseu, Nuts2Region.PT16, "1806"),
            LocalityName.MoimentaDaBeira => (DistrictName.Viseu, Nuts2Region.PT11, "1807"),
            LocalityName.Mortágua => (DistrictName.Viseu, Nuts2Region.PT16, "1808"),
            LocalityName.Nelas => (DistrictName.Viseu, Nuts2Region.PT16, "1809"),
            LocalityName.OliveiraDeFrades => (DistrictName.Viseu, Nuts2Region.PT16, "1810"),
            LocalityName.PenalvaDoCastelo => (DistrictName.Viseu, Nuts2Region.PT16, "1811"),
            LocalityName.Penedono => (DistrictName.Viseu, Nuts2Region.PT11, "1812"),
            LocalityName.Resende => (DistrictName.Viseu, Nuts2Region.PT11, "1813"),
            LocalityName.SantaCombaDão => (DistrictName.Viseu, Nuts2Region.PT16, "1814"),
            LocalityName.SãoJoãoDaPesqueira => (DistrictName.Viseu, Nuts2Region.PT11, "1815"),
            LocalityName.SãoPedroDoSul => (DistrictName.Viseu, Nuts2Region.PT16, "1816"),
            LocalityName.Sátão => (DistrictName.Viseu, Nuts2Region.PT16, "1817"),
            LocalityName.Sernancelhe => (DistrictName.Viseu, Nuts2Region.PT11, "1818"),
            LocalityName.Tabuaço => (DistrictName.Viseu, Nuts2Region.PT11, "1819"),
            LocalityName.Tarouca => (DistrictName.Viseu, Nuts2Region.PT11, "1820"),
            LocalityName.Tondela => (DistrictName.Viseu, Nuts2Region.PT16, "1821"),
            LocalityName.VilaNovaDePaiva => (DistrictName.Viseu, Nuts2Region.PT16, "1822"),
            LocalityName.Viseu => (DistrictName.Viseu, Nuts2Region.PT16, "1823"),
            LocalityName.Vouzela => (DistrictName.Viseu, Nuts2Region.PT16, "1824"),

            // 31 & 32 - R.A. MADEIRA
            LocalityName.CalhetaMadeira => (null, Nuts2Region.PT30, "3101"),
            LocalityName.CâmaraDeLobos => (null, Nuts2Region.PT30, "3102"),
            LocalityName.Funchal => (null, Nuts2Region.PT30, "3103"),
            LocalityName.Machico => (null, Nuts2Region.PT30, "3104"),
            LocalityName.PontaDoSol => (null, Nuts2Region.PT30, "3105"),
            LocalityName.PortoMoniz => (null, Nuts2Region.PT30, "3106"),
            LocalityName.RibeiraBrava => (null, Nuts2Region.PT30, "3107"),
            LocalityName.SantaCruz => (null, Nuts2Region.PT30, "3108"),
            LocalityName.Santana => (null, Nuts2Region.PT30, "3109"),
            LocalityName.SãoVicente => (null, Nuts2Region.PT30, "3110"),
            LocalityName.PortoSanto => (null, Nuts2Region.PT30, "3201"),

            // 41 to 49 - R.A. AÇORES
            LocalityName.VilaDoPorto => (null, Nuts2Region.PT20, "4101"),
            LocalityName.LagoaAçores => (null, Nuts2Region.PT20, "4201"),
            LocalityName.Nordeste => (null, Nuts2Region.PT20, "4202"),
            LocalityName.PontaDelgada => (null, Nuts2Region.PT20, "4203"),
            LocalityName.Povoação => (null, Nuts2Region.PT20, "4204"),
            LocalityName.RibeiraGrande => (null, Nuts2Region.PT20, "4205"),
            LocalityName.VilaFrancaDoCampo => (null, Nuts2Region.PT20, "4206"),
            LocalityName.AngraDoHeroísmo => (null, Nuts2Region.PT20, "4301"),
            LocalityName.PraiaDaVitória => (null, Nuts2Region.PT20, "4302"),
            LocalityName.SantaCruzDaGraciosa => (null, Nuts2Region.PT20, "4401"),
            LocalityName.CalhetaAçores => (null, Nuts2Region.PT20, "4501"),
            LocalityName.Velas => (null, Nuts2Region.PT20, "4502"),
            LocalityName.LajesDoPico => (null, Nuts2Region.PT20, "4601"),
            LocalityName.Madalena => (null, Nuts2Region.PT20, "4602"),
            LocalityName.SãoRoqueDoPico => (null, Nuts2Region.PT20, "4603"),
            LocalityName.Horta => (null, Nuts2Region.PT20, "4701"),
            LocalityName.LajesDasFlores => (null, Nuts2Region.PT20, "4801"),
            LocalityName.SantaCruzDasFlores => (null, Nuts2Region.PT20, "4802"),
            LocalityName.Corvo => (null, Nuts2Region.PT20, "4901"),

            _ => null
        };
    }
}
