

export const DistrictEnum = {
    // "Continente",
    "Aveiro": 1,
    "Beja": 2,
    "Braga": 3,
    "Bragança": 4,
    "Castelo Branco": 5,
    "Coimbra": 6,
    "Évora": 7,
    "Faro": 8,
    "Guarda": 9,
    "Leiria": 10,
    "Lisboa": 11,
    "Portalegre": 12,
    "Porto": 13,
    "Santarém": 14,
    "Setúbal": 15,
    "Viana do Castelo": 16,
    "Vila Real": 17,
    "Viseu": 18,
    // "Arquipelago da Madeira",
    "Ilha da Madeira": 31,
    "Ilha de Porto Santo": 32,
    // "Arquipelago dos Açores",
    "Ilha da Graciosa": 33,
    "Ilha das Flores": 35,
    "Ilha de S. Jorge": 37,
    "Ilha de S. Miguel": 38,
    "Ilha de Santa Maria": 39,
    "Ilha do Corvo": 40,
    "Ilha do Faial": 41,
    "Ilha do Pico": 42,
    "Ilha Terceira": 43
} as const